### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [resetnow/xtensa2arm#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by vlad-ivanov-name** [comment]
Not sure if this issue was created automatically, but nonetheless, rustc-serialize is used by radare2 binding, that's why I'm using it too.

**Comment by dtolnay** [comment]
Thanks for the update! Do you know whether they are planning on moving away from it? Is there an issue on their end?

**Comment by vlad-ivanov-name** [comment]
>whether they are planning on moving away from it

I don't really know — this binding is not that big piece of software, but here's their repo — issue can be opened there https://github.com/radare/r2pipe.rs

**Comment by dtolnay** [comment]
Cool I'll follow up there.

**Comment by dtolnay** [comment]
In https://github.com/radare/r2pipe.rs/issues/19 the r2pipe.rs author says they would welcome a PR to update to Serde. Would you be interested in taking care of that?

**Comment by vlad-ivanov-name** [comment]
I'm quite new to Rust. Also, I'm afraid I don't have enough time for that currently.

**Comment by jrozner** [comment]
Sorry to bump this but I just submitted a PR to fix this. Not sure if they plan to merge it or if this is still relevant, because it's closed, but just wanted to update you.
